version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATABASE: postgres
      PGPORT: 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -p 5432
